version: '3'
services:
  web:
    image: 'django-dev'
    build:
        context: '.'
        dockerfile: Dockerfile
    volumes:
      - .:/code
    depends_on: 
      - db
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - DEBUG_CONFIG=1
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://ubuntu:postgres@db:5432/ubuntu
      - SECRET_KEY=226fs4h!95d3qmi+a=+^23*ny)1s(uxs%%1u+eoq00dc+w2@j
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - DOMAIN_NAME=http://localhost:8000/
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"


  db:
    image: postgres
    environment:
      - POSTGRES_DB=ubuntu
      - POSTGRES_USER=ubuntu
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"