version: '3'
services:
  web:
    image: 'django-dev'
    build:
      context: '.'
      dockerfile: Dockerfile
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://ubuntu:postgres@db:5432/ubuntu
      - SECRET_KEY=226fs4h!95d3qmi+a=+^23*ny)1s(uxs%%1u+eoq00dc+w2@j
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - DOMAIN_NAME=http://localhost:8000/
      - RECAPTCHA_PRIVATE_KEY=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
      - RECAPTCHA_PUBLIC_KEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      - SILENCED_SYSTEM_CHECKS=captcha.recaptcha_test_key_error
      - ADMIN_EMAIL=
      - EMAIL_HOST=
      - EMAIL_USE_TLS=
      - EMAIL_PORT=
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - EMAIL_USE_SSL=
      - DEFAULT_FROM_EMAIL=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_STORAGE_BUCKET_NAME=
      - AWS_S3_REGION_NAME=
      - DJANGO_SUPERUSER_PASSWORD=testadmin
      - DJANGO_SUPERUSER_EMAIL=email@email.com
      - DJANGO_SUPERUSER_USERNAME=testadmin

    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py createsuperuser --noinput --username testadmin || true &&
            python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres
    container_name: postgres-dev
    environment:
      - POSTGRES_DB=ubuntu
      - POSTGRES_USER=ubuntu
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
