# Generated by Django 3.1.8 on 2021-05-03 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='meta_description',
        ),
    ]
