# Generated by Django 3.1.8 on 2021-05-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogindexpage_meta_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Audience Name')),
            ],
        ),
        migrations.AddField(
            model_name='blogpage',
            name='audience',
            field=models.ManyToManyField(related_name='blogposts', to='blog.BlogAudience', verbose_name='Who is the target audience?'),
        ),
    ]
