# Generated by Django 3.1.8 on 2021-04-19 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import uuid
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Audience Name')),
            ],
        ),
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Remote Work Name')),
            ],
        ),
        migrations.CreateModel(
            name='EducationPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Random string for url')),
                ('school_name', models.CharField(max_length=250, verbose_name='School or Company Name')),
                ('degree_offered', models.CharField(max_length=250, verbose_name='Degree or Certificate Name')),
                ('education_description', djrichtextfield.models.RichTextField()),
                ('school_url', models.URLField(blank=True, max_length=250, verbose_name='URL to School')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('audience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.audience', verbose_name='Who is the target audience?')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='Region')),
                ('remote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.remote', verbose_name='Is Remote?')),
                ('subregion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.subregion', verbose_name='Subregion')),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
