# Generated by Django 3.1.8 on 2021-04-30 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationpage',
            name='remote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.remote', verbose_name='Is the Class or Program Remote?'),
        ),
        migrations.AlterField(
            model_name='educationpage',
            name='school_url',
            field=models.URLField(blank=True, max_length=250, verbose_name='URL to School or Company'),
        ),
    ]
