# Generated by Django 3.1.8 on 2021-05-06 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('education', '0002_auto_20210430_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationpage',
            name='subregion',
        ),
        migrations.AddField(
            model_name='educationpage',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='City'),
        ),
    ]
