# Generated by Django 3.1.8 on 2021-05-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20210506_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationpage',
            name='audience',
        ),
        migrations.AddField(
            model_name='educationpage',
            name='audience',
            field=models.ManyToManyField(null=True, to='education.Audience', verbose_name='Who is the target audience?'),
        ),
        migrations.RemoveField(
            model_name='educationpage',
            name='remote',
        ),
        migrations.AddField(
            model_name='educationpage',
            name='remote',
            field=models.ManyToManyField(null=True, to='education.Remote', verbose_name='Is the Class or Program Remote?'),
        ),
    ]
