# Generated by Django 3.1.8 on 2021-05-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20210506_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationpage',
            name='audience',
            field=models.ManyToManyField(related_name='educationposts', to='education.Audience', verbose_name='Who is the target audience?'),
        ),
        migrations.AlterField(
            model_name='educationpage',
            name='remote',
            field=models.ManyToManyField(related_name='educationposts', to='education.Remote', verbose_name='Is the Class or Program Remote?'),
        ),
    ]
