# Generated by Django 3.1.8 on 2021-05-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20210507_0239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audience',
            new_name='EducationAudience',
        ),
        migrations.RenameModel(
            old_name='Remote',
            new_name='EducationRemote',
        ),
    ]
