# Generated by Django 3.1.8 on 2021-05-09 05:51

from __future__ import unicode_literals

import tinymce.models
from django.apps import apps
from django.db import migrations
from django.db.models import F


def copy_field(apps, schema):
    MyModel = apps.get_model('education', 'educationpage')
    MyModel.objects.all().update(education_description_new=F('education_description'))


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20210507_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationpage',
            name='education_description_new',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.RunPython(copy_field),
    ]
