# Generated by Django 3.1.8 on 2021-05-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_educationpage_education_description_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Education Level Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='educationpage',
            name='education_description',
        ),
        migrations.AddField(
            model_name='educationpage',
            name='education_level',
            field=models.ManyToManyField(related_name='educationposts', to='education.EducationLevel', verbose_name='What is the level of education that will be acheived after attending?'),
        ),
    ]
