# Generated by Django 3.1.10 on 2021-06-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20210528_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationpage',
            name='degree_offered',
        ),
        migrations.RemoveField(
            model_name='educationpage',
            name='education_description_new',
        ),
        migrations.RemoveField(
            model_name='educationpage',
            name='remote',
        ),
        migrations.AddField(
            model_name='educationpage',
            name='remote',
            field=models.BooleanField(default=False, verbose_name='Does this School or Company offer remote learning?'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EducationRemote',
        ),
    ]
