# Generated by Django 3.1.8 on 2021-05-03 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='privacypolicypage',
            name='meta_description',
        ),
    ]
