# Generated by Django 3.1.8 on 2021-05-14 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid
import versatileimagefield.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectiveAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Audience Name')),
            ],
        ),
        migrations.CreateModel(
            name='DirectiveDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Applicable diagnosis for directive')),
            ],
        ),
        migrations.CreateModel(
            name='DirectivePopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Applicable population for directive')),
            ],
        ),
        migrations.CreateModel(
            name='DirectivePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Random string for url')),
                ('title', models.CharField(max_length=250, verbose_name='Name or title of directive.')),
                ('directive_description', tinymce.models.HTMLField(null=True)),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('audience', models.ManyToManyField(related_name='educationposts', to='directive.DirectiveAudience', verbose_name='Who is the target audience for this post?')),
                ('diagnosis', models.ManyToManyField(related_name='educationposts', to='directive.DirectiveDiagnosis', verbose_name='What is the target diagnosis?')),
                ('population', models.ManyToManyField(related_name='educationposts', to='directive.DirectivePopulation', verbose_name='Who is the target population?')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='DirectiveImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='directive_images/original/', verbose_name='Image', width_field='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='directive.directivepage')),
            ],
            options={
                'verbose_name': 'Directive Image',
                'verbose_name_plural': 'Directive Images',
            },
        ),
    ]
