# Generated by Django 3.2 on 2021-09-18 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectiveAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Audience Name')),
            ],
        ),
        migrations.CreateModel(
            name='DirectiveDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Applicable diagnosis for directive')),
            ],
        ),
        migrations.CreateModel(
            name='DirectiveIdentifiedPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Identified Patient')),
            ],
        ),
        migrations.CreateModel(
            name='DirectivePopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Applicable population for directive')),
            ],
        ),
        migrations.CreateModel(
            name='DirectivePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Random string for url')),
                ('title', models.CharField(max_length=75, verbose_name='Name or title of directive.')),
                ('intro', models.TextField(max_length=300, null=True, verbose_name='A short intorduction that describes your directive')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('audience', models.ManyToManyField(related_name='educationposts', to='directive.DirectiveAudience', verbose_name='Who is the target audience for this post?')),
                ('diagnosis', models.ManyToManyField(related_name='educationposts', to='directive.DirectiveDiagnosis', verbose_name='What is the target DSM5 diagnosis?')),
                ('identified_patient', models.ManyToManyField(related_name='educationposts', to='directive.DirectiveIdentifiedPatient', verbose_name='Who is the target identified patient?')),
                ('population', models.ManyToManyField(related_name='educationposts', to='directive.DirectivePopulation', verbose_name='Who is the target population?')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
