# Generated by Django 3.2 on 2021-09-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directivepage',
            name='audience',
        ),
        migrations.DeleteModel(
            name='DirectiveAudience',
        ),
    ]
