# Generated by Django 3.1.10 on 2021-06-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectiveIdentifiedPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Identified Patient')),
            ],
        ),
        migrations.AlterField(
            model_name='directivepage',
            name='diagnosis',
            field=models.ManyToManyField(related_name='educationposts', to='directive.DirectiveDiagnosis', verbose_name='What is the target DSM5 diagnosis?'),
        ),
        migrations.AddField(
            model_name='directivepage',
            name='identified_patient',
            field=models.ManyToManyField(related_name='educationposts', to='directive.DirectiveIdentifiedPatient', verbose_name='Who is the target identified patient?'),
        ),
    ]
