# Generated by Django 3.2.5 on 2021-10-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directiveimage',
            name='image',
            field=models.ImageField(upload_to='directives'),
        ),
    ]
