# Generated by Django 3.2.5 on 2021-10-18 01:21

import directive.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive', '0002_alter_directiveimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directiveimage',
            name='image',
            field=models.ImageField(upload_to='directives', validators=[directive.validators.file_size]),
        ),
        migrations.AlterField(
            model_name='directiveinstruction',
            name='instruction',
            field=models.TextField(max_length=2000, verbose_name='Directive Instruction'),
        ),
        migrations.AlterField(
            model_name='directiveobjective',
            name='objective',
            field=models.TextField(max_length=2000, verbose_name='Directive Objectives'),
        ),
        migrations.AlterField(
            model_name='directivepage',
            name='discussion',
            field=models.TextField(max_length=2000, null=True, verbose_name='Directive Dissucssion'),
        ),
    ]
