# Generated by Django 3.2 on 2021-09-18 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directive', '0002_auto_20210918_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectiveInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=250, verbose_name='List of instruction for a particular directive')),
            ],
        ),
        migrations.CreateModel(
            name='DirectiveMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=250, verbose_name='List of materials for a particular directive')),
            ],
        ),
        migrations.CreateModel(
            name='DirectiveObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=250, verbose_name='List of objectives for a particular directive')),
            ],
        ),
        migrations.RemoveField(
            model_name='directivepage',
            name='identified_patient',
        ),
        migrations.AddField(
            model_name='directivepage',
            name='discussion',
            field=models.TextField(max_length=300, null=True, verbose_name='A short intorduction that describes your directive'),
        ),
        migrations.DeleteModel(
            name='DirectiveIdentifiedPatient',
        ),
        migrations.AddField(
            model_name='directiveobjective',
            name='directive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directive.directivepage'),
        ),
        migrations.AddField(
            model_name='directivematerials',
            name='directive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directive.directivepage'),
        ),
        migrations.AddField(
            model_name='directiveinstruction',
            name='directive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directive.directivepage'),
        ),
    ]
