# Generated by Django 3.2 on 2021-09-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive', '0003_auto_20210918_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directiveinstruction',
            name='instruction',
            field=models.CharField(max_length=250, verbose_name='List of instructions for a particular directive'),
        ),
    ]
