# Generated by Django 3.2.11 on 2022-01-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive', '0004_alter_directivepage_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directivepage',
            name='diagnosis',
            field=models.ManyToManyField(help_text='*Use <kbd>CTRL</kbd> + click on windows, or <kbd>CMD ⌘</kbd> + click on a Mac to select more than one.', related_name='educationposts', to='directive.DirectiveDiagnosis', verbose_name='Target Diagnosis'),
        ),
        migrations.AlterField(
            model_name='directivepage',
            name='population',
            field=models.ManyToManyField(help_text='*Use <kbd>CTRL</kbd> + click on windows, or <kbd>CMD ⌘</kbd> + click on a Mac to select more than one.', related_name='educationposts', to='directive.DirectivePopulation', verbose_name='Target Population'),
        ),
    ]
