# Generated by Django 3.2.5 on 2021-12-13 05:10

import directive.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directive', '0004_auto_20211213_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectiveImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='directives', validators=[directive.validators.file_size])),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('directive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='directive.directivepage')),
            ],
        ),
    ]
