# Generated by Django 3.2 on 2021-09-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive', '0005_alter_directivepage_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directivematerials',
            name='directive',
        ),
        migrations.AlterField(
            model_name='directiveobjective',
            name='objective',
            field=models.CharField(max_length=250, verbose_name='Directive Objectives'),
        ),
        migrations.AlterField(
            model_name='directivepage',
            name='diagnosis',
            field=models.ManyToManyField(help_text='*Use ctrl+click on windows, or cmd+click on a Mac to select more than one.', related_name='educationposts', to='directive.DirectiveDiagnosis', verbose_name='Target Diagnosis'),
        ),
        migrations.AlterField(
            model_name='directivepage',
            name='discussion',
            field=models.TextField(max_length=300, null=True, verbose_name='Discussion Description'),
        ),
        migrations.AlterField(
            model_name='directivepage',
            name='intro',
            field=models.TextField(max_length=300, null=True, verbose_name='Directive Introduction'),
        ),
        migrations.AlterField(
            model_name='directivepage',
            name='population',
            field=models.ManyToManyField(help_text='*Use ctrl+click on windows, or cmd+click on a Mac to select more than one.', related_name='educationposts', to='directive.DirectivePopulation', verbose_name='Target Population'),
        ),
        migrations.AlterField(
            model_name='directivepage',
            name='title',
            field=models.CharField(max_length=75, verbose_name='Directive Title'),
        ),
        migrations.DeleteModel(
            name='DirectiveInstruction',
        ),
        migrations.DeleteModel(
            name='DirectiveMaterials',
        ),
    ]
