# Generated by Django 3.2 on 2021-09-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directive', '0006_auto_20210922_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directiveobjective',
            name='directive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='directive.directivepage'),
        ),
    ]
