# Generated by Django 3.2 on 2021-09-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directive', '0007_alter_directiveobjective_directive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directivepage',
            name='discussion',
        ),
    ]
