# Generated by Django 3.2 on 2021-09-26 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directive', '0009_directivematerial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectiveInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=250, verbose_name='Directive Instruction')),
                ('directive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='directive.directivepage')),
            ],
        ),
    ]
