# Generated by Django 3.2 on 2021-09-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directive', '0010_directiveinstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='directivepage',
            name='discussion',
            field=models.TextField(max_length=1000, null=True, verbose_name='Directive Dissucssion'),
        ),
    ]
