# Generated by Django 3.2 on 2021-10-01 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directive', '0011_directivepage_discussion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectiveImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('directive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='directive.directivepage')),
            ],
        ),
    ]
