name: Deployment

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: build web
        run: docker-compose -f docker-compose.ci.yaml up -d

      - name: Check running containers
        run: docker ps -a

      - name: Check logs
        run: docker logs arttherapyguide_web_1

      - name: Run test suite
        run: docker exec arttherapyguide_web_1 python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        ADMIN_EMAIL: ${{ SECRETS.ADMIN_EMAIL }}
        DOMAIN_LIST: ${{ SECRETS.DOMAIN_LIST }}
        CERTBOT_EMAIL: ${{ SECRETS.CERTBOT_EMAIL }}
        DEBUG_CONFIG: ${{ SECRETS.DEBUG_CONFIG }}
        ALLOWED_HOSTS: ${{ SECRETS.ALLOWED_HOSTS }}
        DATABASE_URL: ${{ SECRETS.DATABASE_URL }}
        SECRET_KEY: ${{ SECRETS.SECRET_KEY }}
        EMAIL_BACKEND: ${{ SECRETS.EMAIL_BACKEND }}
        EMAIL_HOST: ${{ SECRETS.EMAIL_HOST }}
        EMAIL_USE_TLS: ${{ SECRETS.EMAIL_USE_TLS }}
        EMAIL_PORT: ${{ SECRETS.EMAIL_PORT }}
        EMAIL_HOST_USER: ${{ SECRETS.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ SECRETS.EMAIL_HOST_PASSWORD }}
        DEFAULT_FROM_EMAIL: ${{ SECRETS.DEFAULT_FROM_EMAIL }}
        RECAPTCHA_PRIVATE_KEY: ${{ SECRETS.RECAPTCHA_PRIVATE_KEY }}
        RECAPTCHA_PUBLIC_KEY: ${{ SECRETS.RECAPTCHA_PUBLIC_KEY }}
        DOMAIN_NAME: ${{ SECRETS.DOMAIN_NAME }}
        AWS_ACCESS_KEY_ID: ${{ SECRETS.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ SECRETS.AWS_SECRET_ACCESS_KEY }}
        AWS_STORAGE_BUCKET_NAME: ${{ SECRETS.AWS_STORAGE_BUCKET_NAME }}
        AWS_S3_REGION_NAME: ${{ SECRETS.AWS_S3_REGION_NAME }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs: DOMAIN_LIST,CERTBOT_EMAIL,DEBUG_CONFIG,ALLOWED_HOSTS,DATABASE_URL,SECRET_KEY,EMAIL_BACKEND,EMAIL_HOST,EMAIL_USE_TLS,EMAIL_PORT,EMAIL_HOST_USER,EMAIL_HOST_PASSWORD,DEFAULT_FROM_EMAIL,RECAPTCHA_PRIVATE_KEY,RECAPTCHA_PUBLIC_KEY,DOMAIN_NAME,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_STORAGE_BUCKET_NAME,AWS_S3_REGION_NAME
        script: export ADMIN_EMAIL=$ADMIN_EMAIL, export CERTBOT_EMAIL=$CERTBOT_EMAIL && export DOMAIN_LIST=$DOMAIN_LIST && export DEBUG_CONFIG=$DEBUG_CONFIG && export ALLOWED_HOSTS=$ALLOWED_HOSTS && export DATABASE_URL=$DATABASE_URL && export SECRET_KEY=$SECRET_KEY && export EMAIL_BACKEND=$EMAIL_BACKEND && export EMAIL_HOST=$EMAIL_HOST && export EMAIL_USE_TLS=$EMAIL_USE_TLS && export EMAIL_PORT=$EMAIL_PORT && export EMAIL_HOST_USER=$EMAIL_HOST_USER && export EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD && export DEFAULT_FROM_EMAIL=$DEFAULT_FROM_EMAIL && export RECAPTCHA_PRIVATE_KEY=$RECAPTCHA_PRIVATE_KEY && export RECAPTCHA_PUBLIC_KEY=$RECAPTCHA_PUBLIC_KEY && export DOMAIN_NAME=$DOMAIN_NAME && export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID && export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY && export AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME && export AWS_S3_REGION_NAME=$AWS_S3_REGION_NAME && cd ~ && rm -rf art-therapy && git clone git@github.com:thisisnotmyuserid/art-therapy.git && docker-compose -f art-therapy/docker-compose.prod.yaml up -d --remove-orphans --build && rm -rf art-therapy